# Generated by Django 2.1.5 on 2019-01-10 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=255)),
                ('aadhar', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('reg_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user_type', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
