# Generated by Django 2.1.5 on 2019-01-10 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAmbulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('accident_location_picture', models.ImageField(blank=True, upload_to='accidents/%Y/%m/%d')),
                ('long', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=50)),
                ('accident_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
