# Generated by Django 2.1.5 on 2019-01-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20190110_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookambulance',
            name='patient_name',
        ),
    ]
