# Generated by Django 2.1.5 on 2019-01-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(db_index=True, max_length=100)),
                ('ambulance_no', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('available', models.BooleanField(blank=True)),
                ('phoneno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
            options={
                'ordering': ('driver_name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='ambulance',
            index_together={('slug',)},
        ),
    ]
